"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import Papa from "papaparse";
import { ArrowRight, CheckCircle2, Download, FileText, Info, Loader2, Scale, ShieldAlert, Sparkles, UploadCloud } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type SourceFirm = { firm_name: string; account_model: string; account_size: number; rules: Record<string, boolean | number | string | null> };
type Metrics = { totalTrades: number; totalBalance: number; peakEquity: number; winRate: number; maxDailyDrawdown: number; overallDrawdown: number; maxDailySwing: number; averageWin: number; averageLoss: number; profitTarget: number; weekendPositions: number; newsTrades: number; tradingDays: number };
type Firm = { id: string; name: string; logoUrl: string; refUrl: string; rules: SourceFirm["rules"]; daily: number; total: number; target: number; drawdownType: string; news: string; weekend: string; minimumDays: number };
type Status = "pass" | "warning" | "fail";
type Line = { label: string; status: Status; detail: string };
type RankedFirm = Firm & { score: number; passed: number; lines: Line[] };

const defaults: Metrics = { totalTrades: 42, totalBalance: 100000, peakEquity: 108400, winRate: 58, maxDailyDrawdown: 4.7, overallDrawdown: 8.4, maxDailySwing: 3.2, averageWin: 420, averageLoss: 260, profitTarget: 11, weekendPositions: 1, newsTrades: 2, tradingDays: 18 };
const steps = ["Parsing trade logs & calculating equity metrics...", "Benchmarking against JSON prop firm rules...", "Generating pass probability matrix & scorecard..."];
const toNumber = (value: unknown) => { const parsed = Number(String(value ?? "").replace(/[^0-9.-]/g, "")); return Number.isFinite(parsed) ? parsed : null; };
const ruleNumber = (rules: Record<string, unknown>, keys: string[], fallback: number) => { for (const key of keys) { const value = toNumber(rules[key]); if (value !== null) return value; } return fallback; };
const logoFor = (name: string) => { const value = name.toLowerCase(); if (value.includes("ftmo")) return "/logos/ftmo-logo.png"; if (value.includes("fundednext")) return "/logos/fundednext-logo.webp"; if (value.includes("5%")) return "/logos/5ers-Logo.png"; if (value.includes("topstep")) return "/logos/topstep-logo.png"; return "/logo.png"; };
const referralFor = (name: string) => { const value = name.toLowerCase(); if (value.includes("ftmo")) return "https://ftmo.com/?ref=propfident"; if (value.includes("fundednext")) return "https://fundednext.com/?ref=propfident"; if (value.includes("funding pips")) return "https://fundingpips.com/?ref=propfident"; if (value.includes("5%")) return "https://www.the5ers.com/?ref=propfident"; return "#pricing"; };

function normalize(firm: SourceFirm, index: number): Firm {
  const rules = firm.rules;
  return { id: `${firm.firm_name}-${firm.account_model}-${firm.account_size}-${index}`, name: `${firm.firm_name} ${firm.account_model} $${Math.round(firm.account_size / 1000)}K`, logoUrl: logoFor(firm.firm_name), refUrl: referralFor(firm.firm_name), rules, daily: ruleNumber(rules, ["daily_drawdown_percent"], 5), total: ruleNumber(rules, ["max_drawdown_percent"], 10), target: ruleNumber(rules, ["profit_target_p1_percent"], 0), drawdownType: `${rules.daily_drawdown_type ?? "unspecified"} / ${rules.max_drawdown_type ?? "unspecified"}`, news: String(rules.news_trading ?? "unspecified"), weekend: String(rules.weekend_holding ?? "unspecified"), minimumDays: ruleNumber(rules, ["min_trading_days_p1"], 0) };
}

async function parseStatement(file: File): Promise<Metrics> {
  return new Promise((resolve, reject) => Papa.parse<Record<string, string>>(file, {
    header: true,
    skipEmptyLines: true,
    complete: ({ data }) => {
      const rows = data.filter((row) => Object.values(row).some(Boolean));
      const values = (names: string[]) => rows.flatMap((row) => { const match = Object.entries(row).find(([key]) => names.some((name) => key.toLowerCase().includes(name))); const value = match ? toNumber(match[1]) : null; return value === null ? [] : [value]; });
      const equity = values(["equity", "balance", "account balance"]);
      const pnl = values(["pnl", "profit", "net profit", "result"]);
      const daily = values(["daily loss", "daily drawdown", "daily dd"]);
      const totalLoss = values(["total loss", "max drawdown", "overall drawdown", "total drawdown"]);
      const wins = pnl.filter((value) => value > 0);
      const losses = pnl.filter((value) => value < 0);
      const peak = equity.reduce((highest, value) => Math.max(highest, value), equity[0] ?? defaults.peakEquity);
      const trough = equity.reduce((lowest, value) => Math.min(lowest, value), peak);
      const dates = new Set(rows.map((row) => Object.entries(row).find(([key]) => /date|time/i.test(key))?.[1]).filter(Boolean));
      resolve({ totalTrades: rows.length || defaults.totalTrades, totalBalance: equity.at(-1) ?? defaults.totalBalance, peakEquity: peak, winRate: pnl.length ? wins.length / pnl.length * 100 : defaults.winRate, maxDailyDrawdown: daily.length ? Math.max(...daily.map(Math.abs)) : defaults.maxDailyDrawdown, overallDrawdown: totalLoss.length ? Math.max(...totalLoss.map(Math.abs)) : peak ? (peak - trough) / peak * 100 : defaults.overallDrawdown, maxDailySwing: daily.length ? Math.max(...daily.map(Math.abs)) : defaults.maxDailySwing, averageWin: wins.length ? wins.reduce((sum, value) => sum + value, 0) / wins.length : defaults.averageWin, averageLoss: losses.length ? Math.abs(losses.reduce((sum, value) => sum + value, 0) / losses.length) : defaults.averageLoss, profitTarget: equity.length ? (equity.at(-1)! - equity[0]) / equity[0] * 100 : defaults.profitTarget, weekendPositions: rows.filter((row) => Object.values(row).some((value) => /weekend|overnight/i.test(String(value)))).length, newsTrades: rows.filter((row) => Object.values(row).some((value) => /news|nfp|fed|cpi|high impact/i.test(String(value)))).length, tradingDays: dates.size || defaults.tradingDays });
    },
    error: reject,
  }));
}

function evaluate(firm: Firm, metrics: Metrics): RankedFirm {
  const dailyMargin = firm.daily - metrics.maxDailyDrawdown;
  const totalMargin = firm.total - metrics.overallDrawdown;
  const newsAllowed = firm.news === "true" || firm.news === "allowed";
  const weekendAllowed = firm.weekend === "true" || firm.weekend === "allowed";
  const ruleStatus = (condition: boolean, warning = false): Status => condition ? "pass" : warning ? "warning" : "fail";
  const lines: Line[] = [
    { label: "Daily drawdown", status: ruleStatus(dailyMargin >= 0, dailyMargin >= -0.5), detail: `${dailyMargin.toFixed(1)}% buffer remaining (${firm.drawdownType.split(" /")[0]})` },
    { label: "Total drawdown", status: ruleStatus(totalMargin >= 0, totalMargin >= -1), detail: `${totalMargin.toFixed(1)}% buffer remaining (${firm.drawdownType.split(" /")[1]})` },
    { label: "Phase 1 profit target", status: ruleStatus(!firm.target || metrics.profitTarget >= firm.target, firm.target > 0 && metrics.profitTarget >= firm.target * .8), detail: `${metrics.profitTarget.toFixed(1)}% achieved / ${firm.target || "none"}% required` },
    { label: "Phase 2 / scaling", status: firm.rules.profit_target_p2_percent == null ? "warning" : "pass", detail: firm.rules.profit_target_p2_percent == null ? "Not specified in JSON.txt" : `${firm.rules.profit_target_p2_percent}% phase 2 target` },
    { label: "News rule", status: ruleStatus(newsAllowed || metrics.newsTrades === 0, !newsAllowed && metrics.newsTrades === 0), detail: newsAllowed ? "Compliant: news allowed" : `${firm.news}; ${metrics.newsTrades} event trades detected` },
    { label: "Weekend / overnight", status: ruleStatus(weekendAllowed || metrics.weekendPositions === 0, !weekendAllowed && metrics.weekendPositions === 0), detail: weekendAllowed ? "Holding allowed" : `${metrics.weekendPositions ? "Close before Friday cutoff" : "No weekend exposure"}` },
    { label: "Minimum trading days", status: ruleStatus(!firm.minimumDays || metrics.tradingDays >= firm.minimumDays, metrics.tradingDays >= firm.minimumDays - 1), detail: firm.minimumDays ? `${metrics.tradingDays} observed / ${firm.minimumDays} required` : "No minimum listed" },
    { label: "Lot / position limits", status: "warning", detail: String(firm.rules.max_lots ?? firm.rules.max_position_size ?? "Not specified") },
    { label: "Consistency / profit cap", status: "warning", detail: String(firm.rules.consistency_rule ?? firm.rules.profit_cap ?? "Not specified") },
    { label: "Payout / profit split", status: "pass", detail: `${firm.rules.profit_split_percent ?? "Unspecified"}% split; cadence ${firm.rules.payout_frequency ?? "not specified"}` },
  ];
  const passed = lines.filter((line) => line.status === "pass").length;
  const weighted = lines.reduce((sum, line) => sum + (line.status === "pass" ? 1 : line.status === "warning" ? .55 : 0), 0);
  return { ...firm, score: Math.round(weighted / lines.length * 100), passed, lines };
}

function StatusIcon({ status }: { status: Status }) { return status === "pass" ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : status === "warning" ? <Info className="h-4 w-4 text-amber-400" /> : <ShieldAlert className="h-4 w-4 text-rose-400" />; }

export function PropMatchEvaluator() {
  const [traderName, setTraderName] = useState("John Doe");
  const [dragging, setDragging] = useState(false);
  const [fileName, setFileName] = useState("");
  const [metrics, setMetrics] = useState(defaults);
  const [firms, setFirms] = useState<Firm[]>([]);
  const [step, setStep] = useState(0);
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/prop-firms").then((response) => response.json() as Promise<SourceFirm[]>).then((data) => setFirms(data.map(normalize))).catch(() => setError("Firm rules could not be loaded.")); }, []);
  const ranked = useMemo(() => firms.map((firm) => evaluate(firm, metrics)).sort((a, b) => b.score - a.score), [firms, metrics]);
  const top = ranked[0];
  const processFile = async (file?: File) => { if (!file || processing) return; if (!/\.(csv|txt)$/i.test(file.name)) { setError("Please upload a .csv or .txt statement."); return; } setError(""); setFileName(file.name); setProcessing(true); setStep(1); try { setMetrics(await parseStatement(file)); setStep(2); await new Promise((resolve) => setTimeout(resolve, 450)); setStep(3); await new Promise((resolve) => setTimeout(resolve, 450)); } catch { setError("Could not parse the statement. Include PnL, equity, or balance columns."); } finally { setProcessing(false); } };
  const downloadCertificate = () => { if (!top) return; const scale = 2; const canvas = document.createElement("canvas"); canvas.width = 1200 * scale; canvas.height = 630 * scale; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.scale(scale, scale); const gradient = ctx.createLinearGradient(0, 0, 1200, 630); gradient.addColorStop(0, "#09090b"); gradient.addColorStop(.55, "#11152a"); gradient.addColorStop(1, "#09090b"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, 1200, 630); ctx.strokeStyle = "#3b82f6"; ctx.strokeRect(24, 24, 1152, 582); ctx.strokeStyle = "#8b5cf6"; ctx.strokeRect(30, 30, 1140, 570); ctx.strokeStyle = "rgba(255,255,255,.04)"; for (let x = 40; x < 1200; x += 40) { ctx.beginPath(); ctx.moveTo(x, 40); ctx.lineTo(x, 590); ctx.stroke(); } for (let y = 40; y < 630; y += 40) { ctx.beginPath(); ctx.moveTo(40, y); ctx.lineTo(1160, y); ctx.stroke(); } ctx.fillStyle = "#f8fafc"; ctx.font = "700 28px sans-serif"; ctx.fillText("PROPFIDENT", 64, 78); ctx.font = "700 30px sans-serif"; ctx.fillText("CERTIFICATE OF COMPLIANCE", 64, 166); ctx.font = "500 16px sans-serif"; ctx.fillStyle = "#cbd5e1"; ctx.fillText(`Trader: ${traderName}`, 64, 202); ctx.fillText(`Verified ${new Date().toLocaleString()}`, 64, 228); ctx.fillStyle = "#a78bfa"; ctx.font = "700 54px sans-serif"; ctx.fillText(`${top.score}%`, 64, 330); ctx.fillStyle = "#f8fafc"; ctx.font = "700 24px sans-serif"; ctx.fillText(top.name, 64, 405); ctx.fillStyle = "#86efac"; ctx.font = "600 13px sans-serif"; ctx.fillText("PROPFIDENT VERIFIED", 64, 438); ctx.fillStyle = "#cbd5e1"; ctx.font = "600 14px sans-serif"; ctx.fillText("TOP 3 FIRM MATCHES", 720, 150); ranked.slice(0, 3).forEach((firm, index) => { const y = 198 + index * 82; ctx.fillStyle = index === 0 ? "#8b5cf6" : "rgba(255,255,255,.09)"; ctx.fillRect(720, y - 25, 390, 48); ctx.fillStyle = "#f8fafc"; ctx.font = "600 14px sans-serif"; ctx.fillText(`${index + 1}. ${firm.name.slice(0, 34)}`, 738, y + 4); ctx.font = "700 18px sans-serif"; ctx.fillText(`${firm.score}%`, 1040, y + 4); }); ctx.font = "500 11px sans-serif"; ctx.fillStyle = "#64748b"; ctx.fillText(`Referral: ${top.refUrl}`, 720, 470); const anchor = document.createElement("a"); anchor.download = `propfident-certificate-${traderName.toLowerCase().replace(/\s+/g, "-")}.png`; anchor.href = canvas.toDataURL("image/png"); anchor.click(); };

  return <div className="space-y-6">
    <Card className="border-border/60 bg-background/50"><CardHeader className="border-b border-border/40"><div className="flex items-center gap-2 text-primary font-mono text-sm"><Scale className="h-4 w-4" /> TOOL 02 // PROP MATCH ENGINE</div><CardTitle>Upload your trading statement</CardTitle></CardHeader><CardContent className="space-y-6 pt-6">
      <div role="button" tabIndex={0} className={`cursor-pointer rounded-xl border-2 border-dashed border-primary/40 bg-primary/5 p-8 text-center transition-all hover:border-primary hover:bg-primary/10 ${dragging ? "border-primary bg-primary/10" : ""}`} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); void processFile(event.dataTransfer.files[0]); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") event.currentTarget.querySelector<HTMLInputElement>("input")?.click(); }}><UploadCloud className="mx-auto h-10 w-10 text-primary" /><h3 className="mt-4 text-lg font-semibold">Drop your trading history here</h3><p className="mx-auto mt-2 max-w-lg text-sm text-muted-foreground">Upload a CSV or TXT statement to calculate equity, drawdown, win rate, and firm-specific pass probability.</p><label className="mt-5 inline-flex cursor-pointer items-center gap-2 rounded-md bg-primary px-5 py-2.5 text-sm text-primary-foreground"><FileText className="h-4 w-4" /> Choose statement<input type="file" accept=".csv,.txt,text/csv,text/plain" className="hidden" onChange={(event) => void processFile(event.target.files?.[0])} /></label><p className="mt-3 text-xs font-mono text-muted-foreground">{fileName || "CSV or TXT only"}</p></div>
      {processing && <div className="rounded-xl border border-primary/20 bg-primary/5 p-5"><div className="mb-4 flex items-center gap-2 text-sm font-semibold"><Loader2 className="h-4 w-4 animate-spin text-primary" /> Processing statement</div>{steps.map((label, index) => <div key={label} className={`flex items-center gap-3 py-1 text-sm ${step > index ? "text-emerald-400" : step === index + 1 ? "text-foreground" : "text-muted-foreground"}`}><span className="flex h-6 w-6 items-center justify-center rounded-full border border-current text-xs">{step > index ? "✓" : index + 1}</span>{label}</div>)}</div>}
      {error && <p className="rounded-md border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</p>}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Total trades", metrics.totalTrades], ["Win rate", `${metrics.winRate.toFixed(1)}%`], ["Peak equity", `$${Math.round(metrics.peakEquity).toLocaleString()}`], ["Max daily swing", `${metrics.maxDailySwing.toFixed(1)}%`], ["Total balance", `$${Math.round(metrics.totalBalance).toLocaleString()}`], ["Avg win", `$${Math.round(metrics.averageWin)}`], ["Avg loss", `$${Math.round(metrics.averageLoss)}`], ["Trading days", metrics.tradingDays]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-border bg-background p-3"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="mt-2 text-lg font-bold">{value}</p></div>)}</div>
    </CardContent></Card>
    {top && <><Card className="border-primary/20 bg-primary/5"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Sparkles className="h-6 w-6 text-primary" /><div><p className="text-xs font-mono uppercase tracking-[0.2em] text-primary">Top recommendation</p><h3 className="text-xl font-semibold">{top.name}</h3></div></div><div className="flex items-center gap-3"><Badge className="bg-emerald-500/10 text-emerald-400">{top.score}% pass probability</Badge><a href={top.refUrl} target="_blank" rel="noreferrer"><Button className="gap-2">Apply now <ArrowRight className="h-4 w-4" /></Button></a></div></CardContent></Card><div className="space-y-3">{ranked.map((firm, index) => <Card key={firm.id} className={index === 0 ? "border-primary/30 bg-primary/5" : "border-border/60"}><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-background font-bold">{index + 1}</div><Image src={firm.logoUrl} alt="" width={36} height={36} className="h-9 w-9 rounded-md object-contain" /><div><p className="font-semibold">{firm.name}</p><p className="text-xs text-muted-foreground">{firm.passed}/{firm.lines.length} rules passed</p></div></div><div className="flex items-center gap-3"><span className="text-xl font-bold">{firm.score}%</span><Dialog><DialogTrigger asChild><Button variant="outline" size="sm">Analyze rules</Button></DialogTrigger><DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{firm.name} rule analysis</DialogTitle><DialogDescription>Evaluated against uploaded trade history and JSON.txt.</DialogDescription></DialogHeader><div className="space-y-2">{firm.lines.map((line) => <div key={line.label} className="flex items-start gap-3 rounded-lg border border-border/60 bg-surface/40 p-3"><StatusIcon status={line.status} /><div><p className="text-sm font-semibold">{line.label}</p><p className="text-xs text-muted-foreground">{line.detail}</p></div><Badge variant="secondary" className="ml-auto text-[10px] uppercase">{line.status}</Badge></div>)}</div><a href={firm.refUrl} target="_blank" rel="noreferrer"><Button className="w-full">View firm offer <ArrowRight className="ml-2 h-4 w-4" /></Button></a></DialogContent></Dialog></div></CardContent></Card>)}</div></>}
    <div className="rounded-[28px] border border-blue-500/60 bg-[linear-gradient(145deg,#09090b,#11152a,#09090b)] p-6 shadow-[0_25px_80px_rgba(59,130,246,0.18)]"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-3"><Image src="/logo.png" alt="Propfident" width={32} height={32} /><div><p className="font-mono text-xs tracking-[0.2em] text-blue-300">PROPFIDENT VERIFIED</p><p className="text-sm text-slate-400">Certificate of compliance</p></div></div><Badge className="bg-violet-500/20 text-violet-200">Top match</Badge></div><div className="mt-6 grid gap-6 md:grid-cols-[1fr_auto]"><div><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Trader</p><input value={traderName} onChange={(event) => setTraderName(event.target.value)} className="mt-2 w-full max-w-md border-b border-white/20 bg-transparent py-2 text-3xl font-bold text-white outline-none" /><p className="mt-5 text-xs uppercase tracking-[0.2em] text-slate-400">Matched firm</p><div className="mt-2 flex items-center gap-3"><Image src={top?.logoUrl ?? "/logo.png"} alt="" width={40} height={40} className="h-10 w-10 rounded-md object-contain" /><span className="text-xl font-semibold text-white">{top?.name ?? "Loading firm rules"}</span></div></div><div className="text-right"><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Pass probability</p><p className="mt-2 text-6xl font-bold text-blue-300">{top?.score ?? 0}%</p></div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-500">1200×630 high-resolution export</p><Button onClick={downloadCertificate} disabled={!top} className="gap-2 bg-blue-600 hover:bg-blue-500"><Download className="h-4 w-4" /> Download Certificate</Button></div></div>
  </div>;
}
